name: "outbox-inbox-and-resillient-pattern-for-message"

services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - rmq_data:/var/lib/rabbitmq

  database:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./consumer/.env
    volumes:
      - rmq_pg_data:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "3002:80"
    restart: "always"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - rmq_pgadmin_data:/var/lib/pgadmin

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database
    stdin_open: true
    tty: true
    env_file:
      - ./producer/.env
    volumes:
      - ./producer/:/src

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    stdin_open: true
    tty: true
    env_file:
      - ./consumer/.env
    volumes:
      - ./consumer/:/src

volumes:
  rmq_pg_data: {}
  rmq_data: {}
  rmq_pgadmin_data: {}